/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CasAdminLogPanel.java
 *
 * Created on 2016-12-09, 12:22:15
 */
package casadmin;
import java.util.*;
import javax.swing.*;
import javax.swing.tree.*;
import javax.swing.border.*;
/**
 *
 * @author lpylypch
 */
public class CasAdminLogPanel extends javax.swing.JPanel {

    /** Creates new form CasAdminLogPanel */
    public CasAdminLogPanel() {
        initComponents();
        fillTree("");
    }

    private void fillTree(String where) {
        // Mapa dla danych w relacji "Data" -> "Przesyłek/Paczek"
        // Tworzymy nowe drzewo
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Log CasAdmin");
        DefaultMutableTreeNode year = null, month = null, day = null, userPerDay = null;
        // Odczytujemy ilość przesyłek i paczek za każdą datę i grupę dat
        Vector<Vector<String> > vAll = GlobalData.oraSession.selectAllRecordsToVector(
          "select * from ( " +
                  "select distinct to_char(INSERTT,'YYYY/MM/DD') || '_' || USERNAME  dd " +
                  "from LOG_CASADMIN " +
                  where +
               "union " +
                  "select distinct to_char(INSERTT,'YYYY/MM/DD') dd " +
                  "from LOG_CASADMIN " +
                  where +
                  "group by to_char(INSERTT,'YYYY/MM/DD') " +
               "union " +
                  "select distinct to_char(INSERTT,'YYYY/MM') dd " +
                  "from LOG_CASADMIN " +
                  where +
                  "group by to_char(INSERTT,'YYYY/MM') " +
               "union " +
                  "select distinct to_char(INSERTT,'YYYY') dd " +
                  "from LOG_CASADMIN " +
                  where +
                  "group by to_char(INSERTT,'YYYY')" +
          ") order by dd",
          new Vector());

        Enumeration en = vAll.elements();

        // Wypełniamy drzewo
        while (en.hasMoreElements()) {
            Vector<String> v = (Vector<String>) en.nextElement();
            String node = v.elementAt(0);
            if (node.length() == 4) { // rok YYYY
                 year = new DefaultMutableTreeNode(node);
                 root.add(year);
            }
            else if (node.length() == 7) { // miesiąc YYYY/MM
                 month = new DefaultMutableTreeNode(node);
                 year.add(month);
            }
            else if (node.length() == 10) { // miesiąc YYYY/MM/DD
                 day = new DefaultMutableTreeNode(node);
                 month.add(day);
            }
            else { // dzień
                 userPerDay = new DefaultMutableTreeNode(node.substring(11));
                 day.add(userPerDay);
            }
        }
        tree.setModel(new DefaultTreeModel(root));

        // Przerysowujemy drzewo
        tree.repaint();

        repaintScreen();
    }
    
    private void repaintScreen() {
        // Zapamiętujemy, jaka data jest wybrana w drzewie
        TreePath path = tree.getSelectionPath();
        if (path != null) {
            DefaultMutableTreeNode selection = (DefaultMutableTreeNode) path.getLastPathComponent();
            String userName = selection.toString();
            if (!userName.startsWith("20")) {
               YPFunctions.enableContainer(panelLog,true);
               String date = selection.getParent().toString();
               Border lowerEtched = BorderFactory.createEtchedBorder(EtchedBorder.LOWERED);
               TitledBorder title = BorderFactory.createTitledBorder(lowerEtched, "Aktywność " + userName + " za " + date);
               panelLog.setBorder(title);
                   
               String query = "SELECT INSERTT, USERNAME, COMPUTERNAME, OPERATIONDESCR, OPERATIONTARGET " +
                              "FROM LOG_CASADMIN " +
                              "where trunc(insertt) = to_date(?, 'YYYY/MM/DD') " +
                              " and username=? order by insertt";
               Vector pars = new Vector(Arrays.asList(date, userName));

               YPFunctions.FillTableFromOra(query,
                                     pars,
                                     0,
                                     99999,
                                     tableLog,
                                     new Vector(),
                                     new Vector(),
                                     false,
                                     false,
                                     new Vector(),
                                     null,
                                     false);
            }
        }
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        upPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        downPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        panelLog = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableLog = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 0));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(CasAdminLogPanel.class);
        jPanel3.setBackground(resourceMap.getColor("jPanel3.background")); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        upPanel.setBackground(resourceMap.getColor("upPanel.background")); // NOI18N
        upPanel.setName("upPanel"); // NOI18N
        upPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setAutoscrolls(true);
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        upPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1000, 80));

        jSplitPane1.setTopComponent(upPanel);

        downPanel.setBackground(resourceMap.getColor("downPanel.background")); // NOI18N
        downPanel.setName("downPanel"); // NOI18N
        downPanel.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane2.setDividerLocation(235);
        jSplitPane2.setName("jSplitPane2"); // NOI18N

        jPanel4.setBackground(resourceMap.getColor("jPanel4.background")); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLog.setBackground(resourceMap.getColor("panelLog.background")); // NOI18N
        panelLog.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelLog.border.title"))); // NOI18N
        panelLog.setName("panelLog"); // NOI18N
        panelLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tableLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableLog.setName("tableLog"); // NOI18N
        tableLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableLogMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableLog);

        panelLog.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 820, 410));

        jPanel4.add(panelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 5, 840, 440));

        jSplitPane2.setRightComponent(jPanel4);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tree.setName("tree"); // NOI18N
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                treeMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tree);

        jSplitPane2.setLeftComponent(jScrollPane1);

        downPanel.add(jSplitPane2);

        jSplitPane1.setRightComponent(downPanel);

        jPanel3.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 560));

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

private void treeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseReleased
        repaintScreen();
}//GEN-LAST:event_treeMouseReleased

private void tableLogMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLogMouseReleased
            int row = tableLog.getSelectedRow();
            int ndx = tableLog.getSelectedColumn();
            String text = YPFunctions.strGet(tableLog,row, ndx);
            if ((ndx >= 3) && (!text.isEmpty()))
            {
                YPFunctions.showMessage(text, "");
            }
}//GEN-LAST:event_tableLogMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel downPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel panelLog;
    private javax.swing.JTable tableLog;
    private javax.swing.JTree tree;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
