package casadmin;

import java.util.*;

public class EditProductDialog extends javax.swing.JDialog {

    /** Creates new form EditProductDialog */
    public EditProductDialog(java.awt.Frame parent, 
                                boolean modal,
                                Vector p_tableRow,
                                boolean p_bInsertOrEdit) {
        super(parent, modal);
        initComponents();
        // Wypełniamy wszystkie ComboBox'y, wykorzystując statyczne zmienne
        // klasy NewUserPanel
        //Wypełniamy comboBox cbProduct ze żródła NewUserPanel.vProducts
        cbProduct.removeAllItems();
        Iterator it = NewUserPanel.vProducts.iterator();
        while (it.hasNext()) {
             cbProduct.addItem(it.next());
        }
        //Wypełniamy comboBox cbPlatnik ze żródła NewUserPanel.mapPlatnik.keySet()
        cbPlatnik.removeAllItems();
        it = NewUserPanel.mapPlatnik.keySet().iterator();
        while (it.hasNext()) {
             cbPlatnik.addItem(it.next());
        }
        //Wypełniamy comboBox cbPlatnosc ze żródła NewUserPanel.mapPlatnosc.keySet()
        cbPlatnosc.removeAllItems();
        it = NewUserPanel.mapPlatnosc.keySet().iterator();
        while (it.hasNext()) {
             cbPlatnosc.addItem(it.next());
        }
        //Wypełniamy comboBox cbEkspres, cbDrobnica ze żródła NewUserPanel.mapPrices.keySet()
        cbEkspres.removeAllItems();
        cbDrobnica.removeAllItems();
        it = NewUserPanel.mapPrices.keySet().iterator();
        while (it.hasNext()) {
             String next = (String)it.next();
             cbEkspres.addItem(next);
             cbDrobnica.addItem(next);
        }
        //Wypełniamy comboBox cbPalety ze żródła NewUserPanel.mapYesNo.keySet()
        cbPalety.removeAllItems();
        it = NewUserPanel.mapYesNo.keySet().iterator();
        while (it.hasNext()) {
             cbPalety.addItem(it.next());
        }

        if (p_tableRow == null)
        {
                // Jeśli przekazany wektor ma wartość "null" - znaczy,
                // że chcemy dodać produkt do listy produktów
                this.setTitle("Dodanie nowego produktu");
        } else {
                // Inaczej czcemy modyfikować zawartość przesyłanych zmiennych.
                // Wybieramy bieżące znaczenia z ComboBox'ów
                cbProduct.setSelectedItem(p_tableRow.elementAt(0));
                cbPlatnik.setSelectedItem(p_tableRow.elementAt(1));
                cbPlatnosc.setSelectedItem(p_tableRow.elementAt(2));
                cbEkspres.setSelectedItem(p_tableRow.elementAt(3));
                cbDrobnica.setSelectedItem(p_tableRow.elementAt(4));
                cbPalety.setSelectedItem(p_tableRow.elementAt(5));
                this.setTitle("Edycja istniejącego produktu");
        }
        // Przy edycji nie pozwalamy zmieniać kluczowych pól
        cbProduct.setEnabled(p_bInsertOrEdit);
        cbPlatnik.setEnabled(p_bInsertOrEdit);
        cbPlatnosc.setEnabled(p_bInsertOrEdit);
        // Program oczekuje na wybieranie nowych wartości w comboBox'ach i
        // zatwierdzenie lub cofanie się.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbPlatnik = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbPlatnosc = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbEkspres = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbDrobnica = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbPalety = new javax.swing.JComboBox();
        jbCancel = new javax.swing.JButton();
        jbOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(EditProductDialog.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cbProduct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProduct.setName("cbProduct"); // NOI18N
        jPanel2.add(cbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, -1));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 20));

        cbPlatnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPlatnik.setName("cbPlatnik"); // NOI18N
        jPanel2.add(cbPlatnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, -1));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 20));

        cbPlatnosc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPlatnosc.setName("cbPlatnosc"); // NOI18N
        jPanel2.add(cbPlatnosc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 160, -1));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 20));

        cbEkspres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEkspres.setName("cbEkspres"); // NOI18N
        jPanel2.add(cbEkspres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, -1));

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, 20));

        cbDrobnica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDrobnica.setName("cbDrobnica"); // NOI18N
        jPanel2.add(cbDrobnica, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 160, -1));

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, 20));

        cbPalety.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPalety.setName("cbPalety"); // NOI18N
        jPanel2.add(cbPalety, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 160, -1));

        jbCancel.setText(resourceMap.getString("jbCancel.text")); // NOI18N
        jbCancel.setName("jbCancel"); // NOI18N
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, -1));

        jbOK.setText(resourceMap.getString("jbOK.text")); // NOI18N
        jbOK.setName("jbOK"); // NOI18N
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });
        jPanel2.add(jbOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // Wcisniety "Cofnij"
        doClose(RET_CANCEL);
}//GEN-LAST:event_jbCancelActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        // Wcisniety "OK"
        doClose(RET_OK);
}//GEN-LAST:event_jbOKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Dialog został zamknięty
        doClose(RET_CANCEL);
    }//GEN-LAST:event_formWindowClosing

    private void doClose(int retStatus) {
        if (retStatus == RET_OK)
        {
            // Użytkownik nacisnął "OK".
            // Przygotowyjemy wektor, który będzie dopisywany lub zamieści inny
            // wektor w tablice
            retVector = new Vector();
            retVector.add(cbProduct.getSelectedItem());
            retVector.add(cbPlatnik.getSelectedItem());
            retVector.add(cbPlatnosc.getSelectedItem());
            retVector.add(cbEkspres.getSelectedItem());
            retVector.add(cbDrobnica.getSelectedItem());
            retVector.add(cbPalety.getSelectedItem());
        }
        // Zamykamy dialog
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**  zwraca informacje o przycisku OK czy Cofnij nacisnął użytkownik
    */
    public int getReturnStatus() {
        // zmienna returnStatus jest prywatna, robimy publiczną metodę,
        // żeby zwrócić informację który przycisk (Ok czy Cofnij) nacisnął
        // użytkownik
        return returnStatus;
    }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditProductDialog dialog = new EditProductDialog(new javax.swing.JFrame(), true,null, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbDrobnica;
    private javax.swing.JComboBox cbEkspres;
    private javax.swing.JComboBox cbPalety;
    private javax.swing.JComboBox cbPlatnik;
    private javax.swing.JComboBox cbPlatnosc;
    private javax.swing.JComboBox cbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    // End of variables declaration//GEN-END:variables
    public int RET_CANCEL = 0;
    public int RET_OK = 1;
    private int returnStatus = RET_CANCEL;
    public Vector retVector;
}
