/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ElenentsDialog.java
 *
 * Created on 2021-06-01, 07:10:24
 */
package casadmin;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import oracle.jdbc.OracleTypes;


/**
 *
 * @author lpylypch
 */
public class ElenentsDialog extends javax.swing.JDialog {

    /** Creates new form ElenentsDialog */
    public ElenentsDialog(java.awt.Frame parent, boolean modal, String pShipmentId) {
        super(parent, modal);
        initComponents();
        String query = "select NUMER_LISTU_PRZEWOZOWEGO, nr_paczki_jjd, waga_rzeczywista, waga_przeliczeniowa, wymiar_x, wymiar_y, wymiar_z, czy_nst, rodzaj_dr," +
                       "       nr_cdex,  KATEGORIA_EX, KATEGORIA_DR, NR_ELEMENTU " +                 
                       "  FROM CAS_DPST.DHL24_PRZESYLKI_PACZKI " +
                       " where NUMER_LISTU_PRZEWOZOWEGO = ?";
        Vector pars = new Vector(Arrays.asList(pShipmentId));

        YPFunctions.FillTableFromOra(query,
                             pars,
                             0,
                             99999,
                             tableElements,
                             new Vector(),
                             new Vector(),
                             false,
                             false,
                             new Vector(),
                             null,
                             false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableElements = new javax.swing.JTable();
        jbClose = new javax.swing.JButton();
        jbSaveCsv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(ElenentsDialog.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableElements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableElements.setName("tableElements"); // NOI18N
        jScrollPane1.setViewportView(tableElements);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1270, 470));

        jbClose.setText(resourceMap.getString("jbClose.text")); // NOI18N
        jbClose.setName("jbClose"); // NOI18N
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, 100, 40));

        jbSaveCsv.setText(resourceMap.getString("jbSaveCsv.text")); // NOI18N
        jbSaveCsv.setName("jbSaveCsv"); // NOI18N
        jbSaveCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveCsvActionPerformed(evt);
            }
        });
        getContentPane().add(jbSaveCsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 490, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        setVisible(false);
        dispose();
}//GEN-LAST:event_jbCloseActionPerformed

private void jbSaveCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveCsvActionPerformed
    YPFunctions.saveTableAsCSV(tableElements); 
}//GEN-LAST:event_jbSaveCsvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElenentsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElenentsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElenentsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElenentsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ElenentsDialog dialog = new ElenentsDialog(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbSaveCsv;
    private javax.swing.JTable tableElements;
    // End of variables declaration//GEN-END:variables
}
