package casadmin;

import java.util.*;
import oracle.jdbc.OracleTypes;


public class ExRabatyDialog extends javax.swing.JDialog {

    public ExRabatyDialog(java.awt.Frame parent,
                                boolean modal, int p_idCas, String p_product, String p_platnik) {
        super(parent, modal);
        initComponents();
        idCas = p_idCas;
        product = p_product;
        platnik = p_platnik;
        showScreen();
    }

    private void showScreen() {
        Vector<Vector> vv = new Vector();
        for(int i = 0; i < 10; i++)
        {
            Vector v = new Vector(Arrays.asList("","0"));
            vv.add(v);
        }

        String dictPalRab_Query = "";
        Vector queryParams = new Vector();
        if (idCas == 0) { // Cennik standardowy DICT_EX_RAB_STD
            dictPalRab_Query =
                "select to_char(volume)," +
                       "to_char(Upust) " +
                "from DICT_EX_RAB_STD " +
                "where " +
                      "id_product=? and " +
                      "id_pay=? " +
                "order by volume";
        
        }
        else {
            dictPalRab_Query =
                "select to_char(volume)," +
                       "to_char(Upust) " +
                "from DICT_EX_RAB " +
                "where id_cust=? and " +
                      "id_product=? and " +
                      "id_pay=? " +
                "order by volume";
            queryParams.add(idCas);
        }
        queryParams.add(product);
        queryParams.add(platnik);

        Vector vvv = GlobalData.oraSession.selectAllRecordsToVector(dictPalRab_Query, queryParams);
        for (int i = 0; i < vvv.size(); i++)
        {
            Vector v1 = (Vector)vvv.elementAt(i);
            vv.set(i, v1);
        }

        YPFunctions.FillTableFromVector(vv,
                new Vector(Arrays.asList("Sztuk do","Upust")),
                tableDiscountCount,
                new Vector(Arrays.asList(30,30)),
                new Vector(),
                false,
                false,
                new Vector(Arrays.asList(0,1)),
                new Vector(),
                false,
                0);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDiscountCount = new javax.swing.JTable();
        jbSaveCountDiscount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(ExRabatyDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCancel.setText(resourceMap.getString("jbCancel.text")); // NOI18N
        jbCancel.setName("jbCancel"); // NOI18N
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 190, 30));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 200, 20));

        jPanel4.setBackground(resourceMap.getColor("jPanel4.background")); // NOI18N
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tableDiscountCount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDiscountCount.setName("tableDiscountCount"); // NOI18N
        jScrollPane2.setViewportView(tableDiscountCount);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 580, 120));

        jbSaveCountDiscount.setText(resourceMap.getString("jbSaveCountDiscount.text")); // NOI18N
        jbSaveCountDiscount.setName("jbSaveCountDiscount"); // NOI18N
        jbSaveCountDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveCountDiscountActionPerformed(evt);
            }
        });
        jPanel4.add(jbSaveCountDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 190, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // Wcisniety "Cofnij"
        doClose(RET_CANCEL);
}//GEN-LAST:event_jbCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Dialog został zamknięty
        doClose(RET_CANCEL);
    }//GEN-LAST:event_formWindowClosing

    private void jbSaveCountDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveCountDiscountActionPerformed
        if (tableDiscountCount.isEditing()) {
            tableDiscountCount.getCellEditor().stopCellEditing();
        }
        int count = 0;
        String data = "";
        
        try {
            for (int i = 0; i < tableDiscountCount.getRowCount(); i++)
            {
                String s = YPFunctions.strGet(tableDiscountCount,i, 0);
                if (!s.equals(""))
                {
                    int volume = Integer.parseInt(YPFunctions.strGet(tableDiscountCount,i, 0));
                    double upust = YPFunctions.nvlParseDouble(YPFunctions.strGet(tableDiscountCount,i, 1));
//                    int upust = Integer.parseInt(YPFunctions.strGet(tableDiscountCount,i, 1));
                    count++;
                    data += volume + ";" + upust + ";";
                }
            }
        } catch (Exception e) {
        }
        
        String s = (String)GlobalData.oraSession.executeFunction(
                   "MGR_DEFINE.F_UPDATE_EX_RAB(?,?,?,?,?)",
                   new Vector(Arrays.asList(idCas, platnik, product, count, data)), OracleTypes.VARCHAR); 
        if (! s.equals("OK")) {
           this.setCursor(java.awt.Cursor.getDefaultCursor());
           YPFunctions.showErrorMessage("Nie udało się wykonać ustawienie słowników [" + s + "]");
           
           return;
        }
        GlobalData.oraSession.SaveLog("Edycja rabatów EX dla ID_CUST=" + idCas,"");

/*
        if (idCas == 0) { // Cennik standardowy DICT_EX_RAB_STD
              GlobalData.oraSession.executeQuery(
                "Delete from dict_EX_rab_std where id_pay=? and id_product=?",
                new Vector(Arrays.asList(platnik, product)));
        } else {
             GlobalData.oraSession.executeQuery(
                "Delete from dict_EX_rab where id_cust=? and id_pay=? and id_product=?",
                new Vector(Arrays.asList(idCas, platnik, product)));
        }

        try {
            for (int i = 0; i < tableDiscountCount.getRowCount(); i++)
            {
                String s = YPFunctions.strGet(tableDiscountCount,i, 0);
                if (!s.equals(""))
                {
                    int volume = Integer.parseInt(YPFunctions.strGet(tableDiscountCount,i, 0));
                    double upust = YPFunctions.nvlParseDouble(YPFunctions.strGet(tableDiscountCount,i, 1));
//                    int upust = Integer.parseInt(YPFunctions.strGet(tableDiscountCount,i, 1));
                    if (idCas == 0) { // Cennik standardowy DICT_EX_RAB_STD
                            GlobalData.oraSession.executeQuery(
                            "INSERT INTO DICT_EX_RAB_STD" +
                                  "(id_product,volume,upust,id_pay)" +
                            "VALUES(?,?,?,?)",
                            new Vector(Arrays.asList(
                                     product,
                                     volume,
                                     upust,
                                     platnik)));
                    } else {
                            GlobalData.oraSession.executeQuery(
                            "INSERT INTO DICT_EX_RAB" +
                                  "(id_cust,id_product,volume,upust,id_pay)" +
                            "VALUES(?,?,?,?,?)",
                            new Vector(Arrays.asList(
                                     idCas,
                                     product,
                                     volume,
                                     upust,
                                     platnik)));
                    }
                }
            }
        } catch (Exception e) {
        }
*/
        showScreen();
        YPFunctions.showMessage("Rabaty zostały zapisane i odczytane","");
    }//GEN-LAST:event_jbSaveCountDiscountActionPerformed

    private void doClose(int retStatus) {
        // Zamykamy dialog
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**  zwraca informacje o przycisku OK czy Cofnij nacisnął użytkownik
    */
    public int getReturnStatus() {
        // zmienna returnStatus jest prywatna, robimy publiczną metodę,
        // żeby zwrócić informację który przycisk (Ok czy Cofnij) nacisnął
        // użytkownik
        return returnStatus;
    }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExRabatyDialog dialog = new ExRabatyDialog(new javax.swing.JFrame(), true,0,"","");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbSaveCountDiscount;
    private javax.swing.JTable tableDiscountCount;
    // End of variables declaration//GEN-END:variables
    public int RET_CANCEL = 0;
    public int RET_OK = 1;
    private int returnStatus = RET_CANCEL;
    public String product;
    public String platnik;
    public int idCas;
}
