package casadmin;

import java.util.*;

public class ReportShipmentsCountPanel extends javax.swing.JPanel {

    public ReportShipmentsCountPanel() {
        initComponents();
        Date d = new Date();
        dcOdDatyNadania.setDate(d);
        dcDoDatyNadania.setDate(d);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        upPanel = new javax.swing.JPanel();
        panelQuery = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dcOdDatyNadania = new com.toedter.calendar.JDateChooser();
        jLabel73 = new javax.swing.JLabel();
        dcDoDatyNadania = new com.toedter.calendar.JDateChooser();
        jbShow = new javax.swing.JButton();
        downPanel = new javax.swing.JPanel();
        panelResult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(ReportShipmentsCountPanel.class);
        upPanel.setBackground(resourceMap.getColor("upPanel.background")); // NOI18N
        upPanel.setName("upPanel"); // NOI18N
        upPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelQuery.setBackground(resourceMap.getColor("panelQuery.background")); // NOI18N
        panelQuery.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelQuery.border.title"))); // NOI18N
        panelQuery.setName("panelQuery"); // NOI18N
        panelQuery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        panelQuery.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        dcOdDatyNadania.setDateFormatString(resourceMap.getString("dcOdDatyNadania.dateFormatString")); // NOI18N
        dcOdDatyNadania.setName("dcOdDatyNadania"); // NOI18N
        panelQuery.add(dcOdDatyNadania, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 20));

        jLabel73.setText(resourceMap.getString("jLabel73.text")); // NOI18N
        jLabel73.setName("jLabel73"); // NOI18N
        panelQuery.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        dcDoDatyNadania.setDateFormatString(resourceMap.getString("dcDoDatyNadania.dateFormatString")); // NOI18N
        dcDoDatyNadania.setName("dcDoDatyNadania"); // NOI18N
        panelQuery.add(dcDoDatyNadania, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, 20));

        jbShow.setText(resourceMap.getString("jbShow.text")); // NOI18N
        jbShow.setName("jbShow"); // NOI18N
        jbShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowActionPerformed(evt);
            }
        });
        panelQuery.add(jbShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 80, -1));

        upPanel.add(panelQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 80));

        jSplitPane1.setTopComponent(upPanel);

        downPanel.setBackground(resourceMap.getColor("downPanel.background")); // NOI18N
        downPanel.setName("downPanel"); // NOI18N
        downPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelResult.setBackground(resourceMap.getColor("panelResult.background")); // NOI18N
        panelResult.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelResult.border.title"))); // NOI18N
        panelResult.setName("panelResult"); // NOI18N
        panelResult.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableResult.setName("tableResult"); // NOI18N
        jScrollPane1.setViewportView(tableResult);

        panelResult.add(jScrollPane1);

        downPanel.add(panelResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 290));

        jSplitPane1.setRightComponent(downPanel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents


    private void jbShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowActionPerformed
        String query =
         "select " +
          "sum(decode(ds.rodzaj,'AH',1,0)) as \"AH\"," +
          "sum(decode(ds.Rodzaj,'09',1,0)) as \"DHL09\"," +
          "sum(decode(ds.Rodzaj,'12',1,0)) as \"DHL12\"," +
          "sum(decode(ds.Rodzaj,'PW',1,0)) as \"PW\"," +
          "sum(decode(ds.Rodzaj,'SM',1,0)) as \"SM\"," +
          "sum(decode(ds.u_blp,'x',1,0)) as \"BLP\" " +
        "from data_shipments ds " +
        "where ds.time between to_date('" +
                    YPFunctions.DateToString(dcOdDatyNadania.getDate()) +
                    " 00:00:00','yyyy/mm/dd hh24:mi:ss')" +
                    " and to_date('" +
                    YPFunctions.DateToString(dcDoDatyNadania.getDate()) +
                    " 23:59:59','yyyy/mm/dd hh24:mi:ss')" +
                  "and ds.is_deleted='N'";


        YPFunctions.clearContainer(panelResult);

        this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        
        YPFunctions.FillTableFromOra(query, null, 0, 99999, tableResult, null, null, false, true, null, null, Boolean.FALSE);
        this.setCursor(java.awt.Cursor.getDefaultCursor());
}//GEN-LAST:event_jbShowActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcDoDatyNadania;
    private com.toedter.calendar.JDateChooser dcOdDatyNadania;
    private javax.swing.JPanel downPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jbShow;
    private javax.swing.JPanel panelQuery;
    private javax.swing.JPanel panelResult;
    private javax.swing.JTable tableResult;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}

