package casadmin;

import java.awt.Dimension;
import java.util.*;

public class ReportLastParcelPanel extends javax.swing.JPanel {

    private boolean findMaxChecked;
    public ReportLastParcelPanel() {
        initComponents();
        tfPaczka.setText("");
        tfLP.setText("");
        findMaxChecked = false;
        buttonOnOff(findMaxChecked);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        upPanel = new javax.swing.JPanel();
        panelQuery = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        tfIdCas = new javax.swing.JTextField();
        jbShowCustomers = new javax.swing.JButton();
        jbShow = new javax.swing.JButton();
        downPanel = new javax.swing.JPanel();
        panelResult = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfPaczka = new javax.swing.JTextField();
        tfLP = new javax.swing.JTextField();
        panelResult1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPaczka1 = new javax.swing.JTextField();
        tfLP1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkAdditionalFind = new javax.swing.JCheckBox();
        buttonFindMax = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(ReportLastParcelPanel.class);
        upPanel.setBackground(resourceMap.getColor("upPanel.background")); // NOI18N
        upPanel.setName("upPanel"); // NOI18N
        upPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelQuery.setBackground(resourceMap.getColor("panelQuery.background")); // NOI18N
        panelQuery.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelQuery.border.title"))); // NOI18N
        panelQuery.setName("panelQuery"); // NOI18N
        panelQuery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setText(resourceMap.getString("jLabel66.text")); // NOI18N
        jLabel66.setName("jLabel66"); // NOI18N
        panelQuery.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, -1));

        tfIdCas.setName("tfIdCas"); // NOI18N
        panelQuery.add(tfIdCas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, 110, 20));

        jbShowCustomers.setText(resourceMap.getString("jbShowCustomers.text")); // NOI18N
        jbShowCustomers.setName("jbShowCustomers"); // NOI18N
        jbShowCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowCustomersActionPerformed(evt);
            }
        });
        panelQuery.add(jbShowCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 25, 40, -1));

        jbShow.setText(resourceMap.getString("jbShow.text")); // NOI18N
        jbShow.setName("jbShow"); // NOI18N
        jbShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowActionPerformed(evt);
            }
        });
        panelQuery.add(jbShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 110, 30));

        upPanel.add(panelQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 60));

        jSplitPane1.setTopComponent(upPanel);

        downPanel.setBackground(resourceMap.getColor("downPanel.background")); // NOI18N
        downPanel.setName("downPanel"); // NOI18N
        downPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelResult.setBackground(resourceMap.getColor("panelResult.background")); // NOI18N
        panelResult.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelResult.border.title"))); // NOI18N
        panelResult.setName("panelResult"); // NOI18N
        panelResult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        panelResult.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        panelResult.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        tfPaczka.setText(resourceMap.getString("tfPaczka.text")); // NOI18N
        tfPaczka.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfPaczka.setName("tfPaczka"); // NOI18N
        tfPaczka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfPaczkaMouseReleased(evt);
            }
        });
        panelResult.add(tfPaczka, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 280, 20));

        tfLP.setText(resourceMap.getString("tfLP.text")); // NOI18N
        tfLP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfLP.setName("tfLP"); // NOI18N
        tfLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfLPMousePressed(evt);
            }
        });
        panelResult.add(tfLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 280, -1));

        downPanel.add(panelResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 100));

        panelResult1.setBackground(resourceMap.getColor("panelResult1.background")); // NOI18N
        panelResult1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelResult1.border.title"))); // NOI18N
        panelResult1.setName("panelResult1"); // NOI18N
        panelResult1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        panelResult1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        panelResult1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        tfPaczka1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfPaczka1.setName("tfPaczka1"); // NOI18N
        tfPaczka1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfPaczka1MouseReleased(evt);
            }
        });
        panelResult1.add(tfPaczka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 280, 20));

        tfLP1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfLP1.setName("tfLP1"); // NOI18N
        tfLP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfLP1MousePressed(evt);
            }
        });
        panelResult1.add(tfLP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 280, -1));

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        panelResult1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, 100));

        checkAdditionalFind.setBackground(resourceMap.getColor("checkAdditionalFind.background")); // NOI18N
        checkAdditionalFind.setText(resourceMap.getString("checkAdditionalFind.text")); // NOI18N
        checkAdditionalFind.setName("checkAdditionalFind"); // NOI18N
        checkAdditionalFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAdditionalFindActionPerformed(evt);
            }
        });
        panelResult1.add(checkAdditionalFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, -1));

        buttonFindMax.setText(resourceMap.getString("buttonFindMax.text")); // NOI18N
        buttonFindMax.setName("buttonFindMax"); // NOI18N
        buttonFindMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFindMaxActionPerformed(evt);
            }
        });
        panelResult1.add(buttonFindMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 330, 40));

        downPanel.add(panelResult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 380, 280));

        jSplitPane1.setRightComponent(downPanel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jbShowCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowCustomersActionPerformed
        // Naciśnięty przycisk "?" w polu "ID CAS"
        // Proponujemy zaznaczyć klientów do przegłądania
        SelectCustomerDialog frame = new SelectCustomerDialog(null, true, true, "", "");
        frame.setTitle("Zaznacz ID_CUST klienta, którego chcesz obejrzeć");
        frame.setVisible(true);
        // Wyświetlamy Id Cust, które chcemy przeglądać
        tfIdCas.setText(((SelectCustomerDialog)frame).selectedID_CUST);
        tfIdCas.repaint();
}//GEN-LAST:event_jbShowCustomersActionPerformed

   private void buttonOnOff(boolean p_onoff)
   {
            buttonFindMax.setEnabled(p_onoff);
   }


    private void jbShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowActionPerformed
        int iIdCas = YPFunctions.nvlParseInteger(tfIdCas.getText());
        if (iIdCas == 0) {
            YPFunctions.showErrorMessage("Nie zaznaczony CUST ID");
            return;
        }
        tfPaczka.setText("");
        tfLP.setText("");
        this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        Vector<String> v = GlobalData.oraSession.selectFirstRecordToVector(
                "select prefix||no_parcel,no_no" +
                " from data_parcels" +
                " where id_cust=? and id=(select max(id)" +
                                         " from data_parcels " +
                                         " where id_cust=?)",
                new Vector(Arrays.asList(iIdCas,iIdCas)));
        this.setCursor(java.awt.Cursor.getDefaultCursor());
        if (v.isEmpty()) {
            YPFunctions.showErrorMessage("Brak danych dla danego CUST ID");
            return;
        }
        tfPaczka.setText(v.elementAt(0));
        tfLP.setText(v.elementAt(1));

}//GEN-LAST:event_jbShowActionPerformed
    private void showShipment(String p_shipment) {
            if (!p_shipment.isEmpty()) {
                YPFunctions.showPanelAsModalDialog(new ShipmentsPanel(
                                                        tfIdCas.getText(),
                                                        p_shipment),
                                                   "Przegląd danych o przesyłkach",
                                                   new Dimension(1017,700));
            }
    }




    private void tfPaczkaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPaczkaMouseReleased
        showShipment(tfLP.getText());
    }//GEN-LAST:event_tfPaczkaMouseReleased

    private void tfLPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfLPMousePressed
        showShipment(tfLP.getText());
    }//GEN-LAST:event_tfLPMousePressed

    private void tfPaczka1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPaczka1MouseReleased
       showShipment(tfLP1.getText());
    }//GEN-LAST:event_tfPaczka1MouseReleased

    private void tfLP1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfLP1MousePressed
       showShipment(tfLP1.getText());
    }//GEN-LAST:event_tfLP1MousePressed

    private void checkAdditionalFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAdditionalFindActionPerformed
        findMaxChecked = ! findMaxChecked;
        buttonOnOff(findMaxChecked);
    }//GEN-LAST:event_checkAdditionalFindActionPerformed

    private void buttonFindMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFindMaxActionPerformed
        int iIdCas = YPFunctions.nvlParseInteger(tfIdCas.getText());
        if (iIdCas == 0) {
            YPFunctions.showErrorMessage("Nie zaznaczony CUST ID");
            return;
        }
        tfPaczka1.setText("");
        tfLP1.setText("");
        this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        Vector<String> v = GlobalData.oraSession.selectFirstRecordToVector(
                "select prefix||no_parcel, no_no from data_parcels " +
                "where id_cust=? and no_parcel=" +
                "(select max(no_parcel) from data_parcels where id_cust=?)",
                new Vector(Arrays.asList(iIdCas, iIdCas)));
        this.setCursor(java.awt.Cursor.getDefaultCursor());
        if (v.isEmpty()) {
            YPFunctions.showErrorMessage("Brak danych dla danego CUST ID");
            return;
        }
        tfPaczka1.setText(v.elementAt(0));
        tfLP1.setText(v.elementAt(1));

    }//GEN-LAST:event_buttonFindMaxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFindMax;
    private javax.swing.JCheckBox checkAdditionalFind;
    private javax.swing.JPanel downPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jbShow;
    private javax.swing.JButton jbShowCustomers;
    private javax.swing.JPanel panelQuery;
    private javax.swing.JPanel panelResult;
    private javax.swing.JPanel panelResult1;
    private javax.swing.JTextField tfIdCas;
    private javax.swing.JTextField tfLP;
    private javax.swing.JTextField tfLP1;
    private javax.swing.JTextField tfPaczka;
    private javax.swing.JTextField tfPaczka1;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
