package casadmin;

import java.awt.Point;
import java.util.*;

public class ReturnsPanel extends javax.swing.JPanel {

    public ReturnsPanel(String p_ShipmentId) {
        initComponents();
        ShowReturn(p_ShipmentId);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShipmentSplitPane = new javax.swing.JSplitPane();
        downDownLeftPanel = new javax.swing.JPanel();
        odbiorcaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NazwaSkrocOdb = new javax.swing.JTextField();
        NazwaOdb = new javax.swing.JTextField();
        KodPocztOdb = new javax.swing.JTextField();
        UlicaOdb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DomOdb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        MiastoOdb = new javax.swing.JTextField();
        nadawcaPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        UlicaNad = new javax.swing.JTextField();
        KodPocztNad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MiastoNad = new javax.swing.JTextField();
        DomNad = new javax.swing.JTextField();
        SkrotNad = new javax.swing.JTextField();
        NazwaNad = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        CountryNad = new javax.swing.JTextField();
        PozDanePanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ZawartPozDane = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        MpkPozDane = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        UwagiPozDane = new javax.swing.JTextField();
        kwotyPanel = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        tfOplPEX = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        tfOplUBE = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        tfOplNstEx = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        tfOplNetto = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        tfOplBrutto = new javax.swing.JTextField();
        jbPdf = new javax.swing.JButton();
        PdfText = new javax.swing.JTextField();
        innePanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        tfTerminalNadawcy = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        tfShipmentId = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        tfCreateDate = new javax.swing.JTextField();
        tfInsertt = new javax.swing.JTextField();
        tfTerminalOdbiorcy = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        tfSource = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfParcelNo = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        tfShipmentIdOrig = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        tfExpireDate = new javax.swing.JTextField();
        checkOrder = new javax.swing.JCheckBox();
        zleceniodawcaPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        UlicaZlec = new javax.swing.JTextField();
        KodPocztZlec = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        MiastoZlec = new javax.swing.JTextField();
        DomZlec = new javax.swing.JTextField();
        SkrotZlec = new javax.swing.JTextField();
        NazwaZlec = new javax.swing.JTextField();
        downDownRightPanel = new javax.swing.JPanel();
        daneLpPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        LpProdukt = new javax.swing.JTextField();
        LpPlatnik = new javax.swing.JTextField();
        LpPk = new javax.swing.JTextField();
        Lp5kg = new javax.swing.JTextField();
        Lp10kg = new javax.swing.JTextField();
        Lp20kg = new javax.swing.JTextField();
        Lp31kg = new javax.swing.JTextField();
        LpNiestandEx = new javax.swing.JTextField();
        LpUbezp = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 0));

        ShipmentSplitPane.setDividerLocation(790);
        ShipmentSplitPane.setName("ShipmentSplitPane"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(ReturnsPanel.class);
        downDownLeftPanel.setBackground(resourceMap.getColor("downDownLeftPanel.background")); // NOI18N
        downDownLeftPanel.setAutoscrolls(true);
        downDownLeftPanel.setMinimumSize(new java.awt.Dimension(80, 80));
        downDownLeftPanel.setName("downDownLeftPanel"); // NOI18N
        downDownLeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        odbiorcaPanel.setBackground(resourceMap.getColor("odbiorcaPanel.background")); // NOI18N
        odbiorcaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("odbiorcaPanel.border.title"))); // NOI18N
        odbiorcaPanel.setName("odbiorcaPanel"); // NOI18N
        odbiorcaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        odbiorcaPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 10));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        odbiorcaPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 20));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        odbiorcaPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 10));

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        odbiorcaPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 10));

        NazwaSkrocOdb.setName("NazwaSkrocOdb"); // NOI18N
        odbiorcaPanel.add(NazwaSkrocOdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, -1));

        NazwaOdb.setName("NazwaOdb"); // NOI18N
        odbiorcaPanel.add(NazwaOdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 240, -1));

        KodPocztOdb.setName("KodPocztOdb"); // NOI18N
        odbiorcaPanel.add(KodPocztOdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        UlicaOdb.setName("UlicaOdb"); // NOI18N
        odbiorcaPanel.add(UlicaOdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 260, -1));

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        odbiorcaPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 20));

        DomOdb.setName("DomOdb"); // NOI18N
        odbiorcaPanel.add(DomOdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 60, -1));

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        odbiorcaPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 20));

        MiastoOdb.setName("MiastoOdb"); // NOI18N
        odbiorcaPanel.add(MiastoOdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 240, -1));

        downDownLeftPanel.add(odbiorcaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 460, 80));

        nadawcaPanel.setBackground(resourceMap.getColor("nadawcaPanel.background")); // NOI18N
        nadawcaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("nadawcaPanel.border.title"))); // NOI18N
        nadawcaPanel.setName("nadawcaPanel"); // NOI18N
        nadawcaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        nadawcaPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 10));

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        nadawcaPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 20));

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        nadawcaPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, 20));

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        nadawcaPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        UlicaNad.setName("UlicaNad"); // NOI18N
        nadawcaPanel.add(UlicaNad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, -1));

        KodPocztNad.setName("KodPocztNad"); // NOI18N
        nadawcaPanel.add(KodPocztNad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        nadawcaPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 20));

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        nadawcaPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 20));

        MiastoNad.setName("MiastoNad"); // NOI18N
        nadawcaPanel.add(MiastoNad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 240, -1));

        DomNad.setName("DomNad"); // NOI18N
        nadawcaPanel.add(DomNad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 50, -1));

        SkrotNad.setName("SkrotNad"); // NOI18N
        nadawcaPanel.add(SkrotNad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, -1));

        NazwaNad.setName("NazwaNad"); // NOI18N
        nadawcaPanel.add(NazwaNad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 240, -1));

        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N
        nadawcaPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 20, 20));

        CountryNad.setName("CountryNad"); // NOI18N
        nadawcaPanel.add(CountryNad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, -1));

        downDownLeftPanel.add(nadawcaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 460, 80));

        PozDanePanel.setBackground(resourceMap.getColor("PozDanePanel.background")); // NOI18N
        PozDanePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("PozDanePanel.border.title"))); // NOI18N
        PozDanePanel.setName("PozDanePanel"); // NOI18N
        PozDanePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        PozDanePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        ZawartPozDane.setName("ZawartPozDane"); // NOI18N
        PozDanePanel.add(ZawartPozDane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, -1));

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        PozDanePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 20));

        MpkPozDane.setName("MpkPozDane"); // NOI18N
        PozDanePanel.add(MpkPozDane, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 180, 20));

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        PozDanePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        UwagiPozDane.setName("UwagiPozDane"); // NOI18N
        PozDanePanel.add(UwagiPozDane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 380, -1));

        downDownLeftPanel.add(PozDanePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 460, 60));

        kwotyPanel.setBackground(resourceMap.getColor("kwotyPanel.background")); // NOI18N
        kwotyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("kwotyPanel.border.title"))); // NOI18N
        kwotyPanel.setName("kwotyPanel"); // NOI18N
        kwotyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setText(resourceMap.getString("jLabel55.text")); // NOI18N
        jLabel55.setName("jLabel55"); // NOI18N
        kwotyPanel.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        tfOplPEX.setFont(resourceMap.getFont("tfOplPEX.font")); // NOI18N
        tfOplPEX.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfOplPEX.setName("tfOplPEX"); // NOI18N
        kwotyPanel.add(tfOplPEX, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 20));

        jLabel57.setText(resourceMap.getString("jLabel57.text")); // NOI18N
        jLabel57.setName("jLabel57"); // NOI18N
        kwotyPanel.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 20, 20));

        tfOplUBE.setFont(resourceMap.getFont("tfOplUBE.font")); // NOI18N
        tfOplUBE.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfOplUBE.setName("tfOplUBE"); // NOI18N
        kwotyPanel.add(tfOplUBE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, 20));

        jLabel61.setText(resourceMap.getString("jLabel61.text")); // NOI18N
        jLabel61.setName("jLabel61"); // NOI18N
        kwotyPanel.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 30, 20));

        tfOplNstEx.setFont(resourceMap.getFont("tfOplNstEx.font")); // NOI18N
        tfOplNstEx.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfOplNstEx.setName("tfOplNstEx"); // NOI18N
        kwotyPanel.add(tfOplNstEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 20));

        jLabel64.setText(resourceMap.getString("jLabel64.text")); // NOI18N
        jLabel64.setName("jLabel64"); // NOI18N
        kwotyPanel.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        tfOplNetto.setFont(resourceMap.getFont("tfOplNetto.font")); // NOI18N
        tfOplNetto.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfOplNetto.setName("tfOplNetto"); // NOI18N
        kwotyPanel.add(tfOplNetto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 20));

        jLabel65.setText(resourceMap.getString("jLabel65.text")); // NOI18N
        jLabel65.setName("jLabel65"); // NOI18N
        kwotyPanel.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 20));

        tfOplBrutto.setFont(resourceMap.getFont("tfOplBrutto.font")); // NOI18N
        tfOplBrutto.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfOplBrutto.setName("tfOplBrutto"); // NOI18N
        kwotyPanel.add(tfOplBrutto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 100, 20));

        downDownLeftPanel.add(kwotyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 310, 60));

        jbPdf.setText(resourceMap.getString("jbPdf.text")); // NOI18N
        jbPdf.setToolTipText(resourceMap.getString("jbPdf.toolTipText")); // NOI18N
        jbPdf.setName("jbPdf"); // NOI18N
        jbPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPdfActionPerformed(evt);
            }
        });
        downDownLeftPanel.add(jbPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 50, 20));

        PdfText.setName("PdfText"); // NOI18N
        downDownLeftPanel.add(PdfText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 730, -1));

        innePanel.setBackground(resourceMap.getColor("innePanel.background")); // NOI18N
        innePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("innePanel.border.title"))); // NOI18N
        innePanel.setName("innePanel"); // NOI18N
        innePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        innePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));

        tfTerminalNadawcy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTerminalNadawcy.setName("tfTerminalNadawcy"); // NOI18N
        innePanel.add(tfTerminalNadawcy, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 30, 20));

        jLabel72.setText(resourceMap.getString("jLabel72.text")); // NOI18N
        jLabel72.setName("jLabel72"); // NOI18N
        innePanel.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        tfShipmentId.setFont(resourceMap.getFont("tfShipmentId.font")); // NOI18N
        tfShipmentId.setName("tfShipmentId"); // NOI18N
        innePanel.add(tfShipmentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 20));

        jLabel69.setText(resourceMap.getString("jLabel69.text")); // NOI18N
        jLabel69.setName("jLabel69"); // NOI18N
        innePanel.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel70.setText(resourceMap.getString("jLabel70.text")); // NOI18N
        jLabel70.setName("jLabel70"); // NOI18N
        innePanel.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 20));

        tfCreateDate.setName("tfCreateDate"); // NOI18N
        innePanel.add(tfCreateDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 70, -1));

        tfInsertt.setName("tfInsertt"); // NOI18N
        innePanel.add(tfInsertt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 110, -1));

        tfTerminalOdbiorcy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTerminalOdbiorcy.setName("tfTerminalOdbiorcy"); // NOI18N
        innePanel.add(tfTerminalOdbiorcy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 30, 20));

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        innePanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabel77.setText(resourceMap.getString("jLabel77.text")); // NOI18N
        jLabel77.setName("jLabel77"); // NOI18N
        innePanel.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        tfSource.setFont(resourceMap.getFont("tfSource.font")); // NOI18N
        tfSource.setName("tfSource"); // NOI18N
        innePanel.add(tfSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 90, 20));

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        innePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        tfParcelNo.setFont(resourceMap.getFont("tfParcelNo.font")); // NOI18N
        tfParcelNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfParcelNo.setName("tfParcelNo"); // NOI18N
        innePanel.add(tfParcelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 240, 20));

        jLabel73.setText(resourceMap.getString("jLabel73.text")); // NOI18N
        jLabel73.setName("jLabel73"); // NOI18N
        innePanel.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        tfShipmentIdOrig.setFont(resourceMap.getFont("tfShipmentIdOrig.font")); // NOI18N
        tfShipmentIdOrig.setName("tfShipmentIdOrig"); // NOI18N
        innePanel.add(tfShipmentIdOrig, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 90, 20));

        jLabel71.setText(resourceMap.getString("jLabel71.text")); // NOI18N
        jLabel71.setName("jLabel71"); // NOI18N
        innePanel.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 20));

        tfExpireDate.setName("tfExpireDate"); // NOI18N
        innePanel.add(tfExpireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 70, -1));

        checkOrder.setBackground(resourceMap.getColor("checkOrder.background")); // NOI18N
        checkOrder.setText(resourceMap.getString("checkOrder.text")); // NOI18N
        checkOrder.setName("checkOrder"); // NOI18N
        innePanel.add(checkOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        downDownLeftPanel.add(innePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 310, 260));

        zleceniodawcaPanel.setBackground(resourceMap.getColor("zleceniodawcaPanel.background")); // NOI18N
        zleceniodawcaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("zleceniodawcaPanel.border.title"))); // NOI18N
        zleceniodawcaPanel.setName("zleceniodawcaPanel"); // NOI18N
        zleceniodawcaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        zleceniodawcaPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 10));

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        zleceniodawcaPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 20));

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        zleceniodawcaPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, 20));

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        zleceniodawcaPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        UlicaZlec.setName("UlicaZlec"); // NOI18N
        zleceniodawcaPanel.add(UlicaZlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 260, -1));

        KodPocztZlec.setName("KodPocztZlec"); // NOI18N
        zleceniodawcaPanel.add(KodPocztZlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        zleceniodawcaPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 20));

        jLabel35.setText(resourceMap.getString("jLabel35.text")); // NOI18N
        jLabel35.setName("jLabel35"); // NOI18N
        zleceniodawcaPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 20));

        MiastoZlec.setName("MiastoZlec"); // NOI18N
        zleceniodawcaPanel.add(MiastoZlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 240, -1));

        DomZlec.setName("DomZlec"); // NOI18N
        zleceniodawcaPanel.add(DomZlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 60, -1));

        SkrotZlec.setName("SkrotZlec"); // NOI18N
        zleceniodawcaPanel.add(SkrotZlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, -1));

        NazwaZlec.setName("NazwaZlec"); // NOI18N
        zleceniodawcaPanel.add(NazwaZlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 240, -1));

        downDownLeftPanel.add(zleceniodawcaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 460, 80));

        ShipmentSplitPane.setLeftComponent(downDownLeftPanel);

        downDownRightPanel.setBackground(resourceMap.getColor("downDownRightPanel.background")); // NOI18N
        downDownRightPanel.setAutoscrolls(true);
        downDownRightPanel.setMinimumSize(new java.awt.Dimension(80, 80));
        downDownRightPanel.setName("downDownRightPanel"); // NOI18N
        downDownRightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daneLpPanel.setBackground(resourceMap.getColor("daneLpPanel.background")); // NOI18N
        daneLpPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("daneLpPanel.border.title"))); // NOI18N
        daneLpPanel.setName("daneLpPanel"); // NOI18N
        daneLpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        daneLpPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N
        daneLpPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N
        daneLpPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N
        daneLpPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel32.setText(resourceMap.getString("jLabel32.text")); // NOI18N
        jLabel32.setName("jLabel32"); // NOI18N
        daneLpPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N
        daneLpPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel34.setText(resourceMap.getString("jLabel34.text")); // NOI18N
        jLabel34.setName("jLabel34"); // NOI18N
        daneLpPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel48.setText(resourceMap.getString("jLabel48.text")); // NOI18N
        jLabel48.setName("jLabel48"); // NOI18N
        daneLpPanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        jLabel50.setName("jLabel50"); // NOI18N
        daneLpPanel.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LpProdukt.setFont(resourceMap.getFont("LpProdukt.font")); // NOI18N
        LpProdukt.setName("LpProdukt"); // NOI18N
        daneLpPanel.add(LpProdukt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, 20));

        LpPlatnik.setFont(resourceMap.getFont("LpPlatnik.font")); // NOI18N
        LpPlatnik.setName("LpPlatnik"); // NOI18N
        daneLpPanel.add(LpPlatnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, 20));

        LpPk.setFont(resourceMap.getFont("LpPk.font")); // NOI18N
        LpPk.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        LpPk.setName("LpPk"); // NOI18N
        daneLpPanel.add(LpPk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 20));

        Lp5kg.setFont(resourceMap.getFont("Lp5kg.font")); // NOI18N
        Lp5kg.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Lp5kg.setName("Lp5kg"); // NOI18N
        daneLpPanel.add(Lp5kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, 20));

        Lp10kg.setFont(resourceMap.getFont("Lp10kg.font")); // NOI18N
        Lp10kg.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Lp10kg.setName("Lp10kg"); // NOI18N
        daneLpPanel.add(Lp10kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, 20));

        Lp20kg.setFont(resourceMap.getFont("Lp20kg.font")); // NOI18N
        Lp20kg.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Lp20kg.setName("Lp20kg"); // NOI18N
        daneLpPanel.add(Lp20kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, 20));

        Lp31kg.setFont(resourceMap.getFont("Lp31kg.font")); // NOI18N
        Lp31kg.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Lp31kg.setName("Lp31kg"); // NOI18N
        daneLpPanel.add(Lp31kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 20));

        LpNiestandEx.setFont(resourceMap.getFont("LpNiestandEx.font")); // NOI18N
        LpNiestandEx.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        LpNiestandEx.setName("LpNiestandEx"); // NOI18N
        daneLpPanel.add(LpNiestandEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 90, 20));

        LpUbezp.setFont(resourceMap.getFont("LpUbezp.font")); // NOI18N
        LpUbezp.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        LpUbezp.setName("LpUbezp"); // NOI18N
        daneLpPanel.add(LpUbezp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 90, 20));

        jLabel51.setText(resourceMap.getString("jLabel51.text")); // NOI18N
        jLabel51.setName("jLabel51"); // NOI18N
        daneLpPanel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        downDownRightPanel.add(daneLpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 350));

        ShipmentSplitPane.setRightComponent(downDownRightPanel);

        add(ShipmentSplitPane);
    }// </editor-fold>//GEN-END:initComponents

private void jbPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPdfActionPerformed
    ShowShipmentDetailsDialog frame = new ShowShipmentDetailsDialog(null, true, PdfText.getText());
    frame.setVisible(true);
}//GEN-LAST:event_jbPdfActionPerformed

    private void ShowReturn(String p_ShipmentId) {
        // Oczyszczanie pól JTextField, JCheckBox, JTable
        YPFunctions.clearContainer(ShipmentSplitPane);

        // Numer LP
        tfShipmentId.setText(p_ShipmentId);

        // Dane przesyłki, zapisane w formacie dla wydruku w kodzie PDF417
        String query = "select pdf, source from data_ship_pdf where no_no=? order by id desc";
        Vector pars = new Vector(Arrays.asList(p_ShipmentId));

        Vector<String> v = GlobalData.oraSession.selectFirstRecordToVector(query, pars);
        if (!v.isEmpty()) {
            PdfText.setText(v.elementAt(0));
            PdfText.setCaretPosition(0);
            tfSource.setText(v.elementAt(1));
        }
        
        
        String clientQuery = "SELECT NAME, SHORTNAME, ADDR_ZIPCODE, ADDR_CITY, ADDR_STREET, ADDR_STREETNO, " +
                                 "ADDR_COUNTRY " +
                             "FROM wspolne_dane_terminali.RETURN_CLIENTS where id = ?";
//        String sapQuery = "select NAZWA,id_sap,KOD_P,MIASTO,ULICA,NR_DOMU,'PL' from customers_sap where id_sap=?";
        
        String sapQuery = "select BORSOFT.DECODEDATA(NAZWA),Id_sap,BORSOFT.DECODEDATA(KOD_P)," +
                "BORSOFT.DECODEDATA(MIASTO),BORSOFT.DECODEDATA(ULICA),BORSOFT.DECODEDATA(NR_DOMU),'PL' " +
                "from SAP.KLSAP@SPS where Id_sap=?";

        

        Vector<String> mainData = GlobalData.oraSession.selectFirstRecordToVector(
         "SELECT NO_NO, RODZAJ, PKT_NAD_REGION, PKT_ODB_REGION, NADAWCA_ID, ODBIORCA_ID, ZLECENIODAWCA_ID," +
           "KAT0, KAT1, KAT2, KAT3, KAT4,PLATNIK, PLATNOSC, SENDESCR, WARTOSC, OPL_UBEZP, SPERGT, OPL_SPERGT," + 
           "TOTAL_NETTO, TOTAL_BRUTTO, UWAGI, TIME, INSERTT, OS_KONT, NUMER_PACZKI,EXP_DATE, BOOK_COURIER," + 
           "RELATED_WAYBILL_NUMBER, Content, nadawca_sap, odbiorca_sap, zleceniodawca_sap " +  // 30,31,32
         "FROM wspolne_dane_terminali.RETURN_SHIPMENTS where no_no=?", pars);
        
        if ((mainData == null) || (mainData.size() == 0))
        {
            YPFunctions.showErrorMessage("Dane w przesyłce zwrotnej nie zostały zapisane na serwerze z powodu błędnego formatu danych");
            return;
        }

        
        Vector<String> nadData = GlobalData.oraSession.selectFirstRecordToVector(clientQuery, 
                new Vector(Arrays.asList(mainData.elementAt(4))));
        
        Vector<String> odbData = null;
        
        try {
          if (mainData.elementAt(12).equals("O") && mainData.elementAt(13).equals("P"))
          {
                odbData = GlobalData.oraSession.selectFirstRecordToVector(sapQuery, 
                    new Vector(Arrays.asList(mainData.elementAt(31))));
          }
          else
          {
            if (mainData.elementAt(5).startsWith("M"))
                odbData = GlobalData.oraSession.selectFirstRecordToVector(clientQuery, 
                    new Vector(Arrays.asList(mainData.elementAt(5))));
            }
        }
        catch (Exception e) {
        }

        if ((odbData == null) || (odbData.size() == 0))
            odbData = new Vector(Arrays.asList("","","","","","",""));

        
        
        
        
        Vector<String> zlecData = null;
        
        try {
          if (mainData.elementAt(12).equals("Z") && mainData.elementAt(13).equals("P"))
          {
                zlecData = GlobalData.oraSession.selectFirstRecordToVector(sapQuery, 
                    new Vector(Arrays.asList(mainData.elementAt(32))));
          }
          else
          {
                if (mainData.elementAt(6).startsWith("M"))
                    zlecData = GlobalData.oraSession.selectFirstRecordToVector(clientQuery, 
                        new Vector(Arrays.asList(mainData.elementAt(6))));
          }    
        }
        catch (Exception ex) {
        }
        if ((zlecData == null) || (zlecData.size() == 0))
            zlecData = new Vector(Arrays.asList("","","","","","",""));

        
        
        NazwaSkrocOdb.setText(odbData.elementAt(1));
        NazwaOdb.setText(odbData.elementAt(0));
        KodPocztOdb.setText(odbData.elementAt(2));
        MiastoOdb.setText(odbData.elementAt(3));
        UlicaOdb.setText(odbData.elementAt(4));
        DomOdb.setText(odbData.elementAt(5));

        SkrotNad.setText(nadData.elementAt(1));
        NazwaNad.setText(nadData.elementAt(0));
        KodPocztNad.setText(nadData.elementAt(2));
        MiastoNad.setText(nadData.elementAt(3));
        UlicaNad.setText(nadData.elementAt(4));
        DomNad.setText(nadData.elementAt(5));
        CountryNad.setText(nadData.elementAt(6));
        
        SkrotZlec.setText(zlecData.elementAt(1));
        NazwaZlec.setText(zlecData.elementAt(0));
        KodPocztZlec.setText(zlecData.elementAt(2));
        MiastoZlec.setText(zlecData.elementAt(3));
        UlicaZlec.setText(zlecData.elementAt(4));
        DomZlec.setText(zlecData.elementAt(5));
        
        ZawartPozDane.setText(mainData.elementAt(29));
        MpkPozDane.setText(mainData.elementAt(14));
        UwagiPozDane.setText(mainData.elementAt(21));
        
        if (mainData.elementAt(22).length() >= 10)
           tfCreateDate.setText(mainData.elementAt(22).substring(0, 10));
        tfTerminalNadawcy.setText(mainData.elementAt(2));
        tfTerminalOdbiorcy.setText(mainData.elementAt(3));
        tfInsertt.setText(mainData.elementAt(23));
        tfParcelNo.setText(mainData.elementAt(25));
        tfShipmentIdOrig.setText(mainData.elementAt(28));
        if (mainData.elementAt(26).length() >= 10)
           tfExpireDate.setText(mainData.elementAt(26).substring(0, 10));
        checkOrder.setSelected(mainData.elementAt(27).equals("T"));
        
        
        
        tfOplPEX.setText("0.00");
        tfOplUBE.setText(String.format("%1.2f", YPFunctions.nvlParseDouble(mainData.elementAt(16))));
        tfOplNstEx.setText(String.format("%1.2f", YPFunctions.nvlParseDouble(mainData.elementAt(18))));
        tfOplNetto.setText(String.format("%1.2f", YPFunctions.nvlParseDouble(mainData.elementAt(19))));
        tfOplBrutto.setText(String.format("%1.2f", YPFunctions.nvlParseDouble(mainData.elementAt(20))));
        
        LpProdukt.setText(mainData.elementAt(1));
        LpPlatnik.setText(mainData.elementAt(12) + mainData.elementAt(13));
        LpPk.setText(mainData.elementAt(7));
        Lp5kg.setText(mainData.elementAt(8));
        Lp10kg.setText(mainData.elementAt(9));
        Lp20kg.setText(mainData.elementAt(10));
        Lp31kg.setText(mainData.elementAt(11));
        LpNiestandEx.setText(mainData.elementAt(17));
        LpUbezp.setText(String.format("%1.2f", YPFunctions.nvlParseDouble(mainData.elementAt(15))));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CountryNad;
    private javax.swing.JTextField DomNad;
    private javax.swing.JTextField DomOdb;
    private javax.swing.JTextField DomZlec;
    private javax.swing.JTextField KodPocztNad;
    private javax.swing.JTextField KodPocztOdb;
    private javax.swing.JTextField KodPocztZlec;
    private javax.swing.JTextField Lp10kg;
    private javax.swing.JTextField Lp20kg;
    private javax.swing.JTextField Lp31kg;
    private javax.swing.JTextField Lp5kg;
    private javax.swing.JTextField LpNiestandEx;
    private javax.swing.JTextField LpPk;
    private javax.swing.JTextField LpPlatnik;
    private javax.swing.JTextField LpProdukt;
    private javax.swing.JTextField LpUbezp;
    private javax.swing.JTextField MiastoNad;
    private javax.swing.JTextField MiastoOdb;
    private javax.swing.JTextField MiastoZlec;
    private javax.swing.JTextField MpkPozDane;
    private javax.swing.JTextField NazwaNad;
    private javax.swing.JTextField NazwaOdb;
    private javax.swing.JTextField NazwaSkrocOdb;
    private javax.swing.JTextField NazwaZlec;
    private javax.swing.JTextField PdfText;
    private javax.swing.JPanel PozDanePanel;
    private javax.swing.JSplitPane ShipmentSplitPane;
    private javax.swing.JTextField SkrotNad;
    private javax.swing.JTextField SkrotZlec;
    private javax.swing.JTextField UlicaNad;
    private javax.swing.JTextField UlicaOdb;
    private javax.swing.JTextField UlicaZlec;
    private javax.swing.JTextField UwagiPozDane;
    private javax.swing.JTextField ZawartPozDane;
    private javax.swing.JCheckBox checkOrder;
    private javax.swing.JPanel daneLpPanel;
    private javax.swing.JPanel downDownLeftPanel;
    private javax.swing.JPanel downDownRightPanel;
    private javax.swing.JPanel innePanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbPdf;
    private javax.swing.JPanel kwotyPanel;
    private javax.swing.JPanel nadawcaPanel;
    private javax.swing.JPanel odbiorcaPanel;
    private javax.swing.JTextField tfCreateDate;
    private javax.swing.JTextField tfExpireDate;
    private javax.swing.JTextField tfInsertt;
    private javax.swing.JTextField tfOplBrutto;
    private javax.swing.JTextField tfOplNetto;
    private javax.swing.JTextField tfOplNstEx;
    private javax.swing.JTextField tfOplPEX;
    private javax.swing.JTextField tfOplUBE;
    private javax.swing.JTextField tfParcelNo;
    private javax.swing.JTextField tfShipmentId;
    private javax.swing.JTextField tfShipmentIdOrig;
    private javax.swing.JTextField tfSource;
    private javax.swing.JTextField tfTerminalNadawcy;
    private javax.swing.JTextField tfTerminalOdbiorcy;
    private javax.swing.JPanel zleceniodawcaPanel;
    // End of variables declaration//GEN-END:variables
    private int iStartRecord;
}
