package casadmin;

import java.util.*;

public class SelectSortFieldsDialog extends javax.swing.JDialog {

    /** Creates new form EditProductDialog */
    public SelectSortFieldsDialog(java.awt.Frame parent, 
                                boolean modal,
                                String sTableName,
                                final Vector<String> vFields) {
        super(parent, modal);
        initComponents();
        vSelectedFields = new Vector();
        labelTableView.setText("Tabela/Widok " + sTableName);
        sourceModel = new YPListModel();
        sourceModel.addAll(vFields);
        listSource.setModel(sourceModel);
        destModel = new YPListModel();
        listDest.setModel(destModel);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCancel = new javax.swing.JButton();
        jbOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSource = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDest = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTableView = new javax.swing.JLabel();
        butAdd = new javax.swing.JButton();
        butDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(SelectSortFieldsDialog.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCancel.setText(resourceMap.getString("jbCancel.text")); // NOI18N
        jbCancel.setName("jbCancel"); // NOI18N
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 110, 30));

        jbOK.setText(resourceMap.getString("jbOK.text")); // NOI18N
        jbOK.setName("jbOK"); // NOI18N
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 110, 30));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listSource.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listSource.setName("listSource"); // NOI18N
        listSource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listSourceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listSource);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 220));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        listDest.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listDest.setDragEnabled(true);
        listDest.setName("listDest"); // NOI18N
        listDest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listDest);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 240, 220));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, -1));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        labelTableView.setText(resourceMap.getString("labelTableView.text")); // NOI18N
        labelTableView.setName("labelTableView"); // NOI18N
        jPanel1.add(labelTableView, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, -1));

        butAdd.setText(resourceMap.getString("butAdd.text")); // NOI18N
        butAdd.setName("butAdd"); // NOI18N
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });
        jPanel1.add(butAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, -1));

        butDel.setText(resourceMap.getString("butDel.text")); // NOI18N
        butDel.setName("butDel"); // NOI18N
        butDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDelActionPerformed(evt);
            }
        });
        jPanel1.add(butDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // Wcisniety "Cofnij"
        doClose(RET_CANCEL);
}//GEN-LAST:event_jbCancelActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        // Wcisniety "OK"
        doClose(RET_OK);
}//GEN-LAST:event_jbOKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Dialog został zamknięty
        doClose(RET_CANCEL);
    }//GEN-LAST:event_formWindowClosing

public void addDestinationElements(Object newValue[]) {
    fillListModel(destModel, newValue);
  }

  private void fillListModel(YPListModel model, Object newValues[]) {
    model.addAll(newValues);
  }

  private void clearSourceSelected() {
    Object selected[] = listSource.getSelectedValues();
    for (int i = selected.length - 1; i >= 0; --i) {
      sourceModel.removeElement((String)selected[i]);
    }
    listSource.getSelectionModel().clearSelection();
  }

  public void addSourceElements(Object newValue[]) {
    fillListModel(sourceModel, newValue);
  }

  private void clearDestinationSelected() {
    Object selected[] = listDest.getSelectedValues();
    for (int i = selected.length - 1; i >= 0; --i) {
      destModel.removeElement((String)selected[i]);
    }
    listDest.getSelectionModel().clearSelection();
  }

    private void addField()
    {
       Object selected[] = listSource.getSelectedValues();
       addDestinationElements(selected);
       clearSourceSelected();
    }

    private void delField()
    {
        Object selected[] = listDest.getSelectedValues();
        addSourceElements(selected);
        clearDestinationSelected();
    }


    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
      addField();
    }//GEN-LAST:event_butAddActionPerformed

    private void butDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDelActionPerformed
      delField();
    }//GEN-LAST:event_butDelActionPerformed

    private void listSourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSourceMouseClicked
        if (evt.getClickCount() == 2)
            addField();
    }//GEN-LAST:event_listSourceMouseClicked

    private void listDestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDestMouseClicked
        if (evt.getClickCount() == 2)
            delField();
    }//GEN-LAST:event_listDestMouseClicked

    private void doClose(int retStatus) {
        if (retStatus == RET_OK)
        {
           vSelectedFields = destModel.model;
            // Użytkownik nacisnął "OK".
            // Przygotowujemy wektor, który będzie dopisywany lub zamieści inny
            // wektor w tablice
//            retVector.add(cbProduct.getSelectedItem());
        }
        // Zamykamy dialog
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**  zwraca informacje o przycisku OK czy Cofnij nacisnął użytkownik
    */
    public int getReturnStatus() {
        // zmienna returnStatus jest prywatna, robimy publiczną metodę,
        // żeby zwrócić informację który przycisk (Ok czy Cofnij) nacisnął
        // użytkownik
        return returnStatus;
    }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectSortFieldsDialog dialog = new SelectSortFieldsDialog(new javax.swing.JFrame(), true,"",null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JLabel labelTableView;
    private javax.swing.JList listDest;
    private javax.swing.JList listSource;
    // End of variables declaration//GEN-END:variables
    private YPListModel sourceModel;
    private YPListModel destModel;

    public int RET_CANCEL = 0;
    public int RET_OK = 1;
    private int returnStatus = RET_CANCEL;
    public Vector<String> vSelectedFields;
}
