package casadmin;

import java.util.*;


public class SettingsDialog extends javax.swing.JDialog {

    public SettingsDialog(java.awt.Frame parent,
                                boolean modal) {
        super(parent, modal);
        initComponents();
        showScreen();
    }

    private void showScreen() {
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbClose = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        checkGif = new javax.swing.JCheckBox();
        checkColumnsOrder = new javax.swing.JCheckBox();
        checkColumnsWidth = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        dcOdDaty = new com.toedter.calendar.JDateChooser();
        jbSaveSettings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(SettingsDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbClose.setText(resourceMap.getString("jbClose.text")); // NOI18N
        jbClose.setName("jbClose"); // NOI18N
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 120, 30));

        jPanel4.setBackground(resourceMap.getColor("jPanel4.background")); // NOI18N
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkGif.setBackground(resourceMap.getColor("checkGif.background")); // NOI18N
        checkGif.setText(resourceMap.getString("checkGif.text")); // NOI18N
        checkGif.setName("checkGif"); // NOI18N
        jPanel4.add(checkGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        checkColumnsOrder.setBackground(resourceMap.getColor("checkColumnsOrder.background")); // NOI18N
        checkColumnsOrder.setText(resourceMap.getString("checkColumnsOrder.text")); // NOI18N
        checkColumnsOrder.setName("checkColumnsOrder"); // NOI18N
        jPanel4.add(checkColumnsOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 350, -1));

        checkColumnsWidth.setBackground(resourceMap.getColor("checkColumnsWidth.background")); // NOI18N
        checkColumnsWidth.setText(resourceMap.getString("checkColumnsWidth.text")); // NOI18N
        checkColumnsWidth.setName("checkColumnsWidth"); // NOI18N
        jPanel4.add(checkColumnsWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 280, -1));

        dcOdDaty.setName("dcOdDaty"); // NOI18N
        jPanel4.add(dcOdDaty, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 90, 110, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 200));

        jbSaveSettings.setText(resourceMap.getString("jbSaveSettings.text")); // NOI18N
        jbSaveSettings.setName("jbSaveSettings"); // NOI18N
        jbSaveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveSettingsActionPerformed(evt);
            }
        });
        jPanel1.add(jbSaveSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        // Wcisniety "Cofnij"
        doClose(RET_CANCEL);
}//GEN-LAST:event_jbCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Dialog został zamknięty
        doClose(RET_CANCEL);
    }//GEN-LAST:event_formWindowClosing

    private void jbSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveSettingsActionPerformed
        showScreen();
    }//GEN-LAST:event_jbSaveSettingsActionPerformed

    private void doClose(int retStatus) {
        // Zamykamy dialog
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**  zwraca informacje o przycisku OK czy Cofnij nacisnął użytkownik
    */
    public int getReturnStatus() {
        // zmienna returnStatus jest prywatna, robimy publiczną metodę,
        // żeby zwrócić informację który przycisk (Ok czy Cofnij) nacisnął
        // użytkownik
        return returnStatus;
    }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SettingsDialog dialog = new SettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkColumnsOrder;
    private javax.swing.JCheckBox checkColumnsWidth;
    private javax.swing.JCheckBox checkGif;
    private com.toedter.calendar.JDateChooser dcOdDaty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbSaveSettings;
    // End of variables declaration//GEN-END:variables
    public int RET_CANCEL = 0;
    public int RET_OK = 1;
    private int returnStatus = RET_CANCEL;
}
