

package casadmin;

public class SystemUsersPanel extends javax.swing.JPanel {

    public SystemUsersPanel() {
        initComponents();
        // Wypełniamy tablicę
        String showPassword = "";
        if (Integer.parseInt(GlobalData.m_sGrant) == 1)
                showPassword = "user_pass,";
        YPFunctions.FillTableFromOra("select id_user,user_name,"+
                                      showPassword +
                                     "id_grant,active,first_name,last_name from cas_users",
                                     null,
                                     0,
                                     99999,
                                     tableUsers,
                                     null,
                                     null,
                                     false,
                                     true,
                                     null,
                                     null,
                                     true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(casadmin.CasAdminApp.class).getContext().getResourceMap(SystemUsersPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUsers.setName("tableUsers"); // NOI18N
        jScrollPane1.setViewportView(tableUsers);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUsers;
    // End of variables declaration//GEN-END:variables

}
